Repository 2024-Summer-Bootcamp-Team-O/Frontend, pull requests merged in 2024-07, with the labels that each got.

#5 design: 시작페이지 수정 및 gitignore 설정
  .gitignore
  src/App.tsx
  src/StartPage.css
  src/index.css
  src/main.tsx
  src/pages/StartPage.tsx
  tailwind.config.js
Labels: 🎨Design

#13 design: 회원가입 페이지 구현
  src/App.tsx
  src/main.tsx
  src/pages/LoginPage.tsx
  src/pages/RegisterPage.tsx
Labels: 🎨Design

#17 [design/#8] 메인페이지 퍼블리싱
  src/App.tsx
  src/assets/images/Character/cardSd_1.png
  src/assets/images/Character/cardSd_2.png
  src/assets/images/Character/cardSd_3.png
  src/assets/images/Character/cardSd_4.png
  src/assets/images/Character/cardSd_5.png
  src/assets/images/Character/cardSd_a.png
  src/assets/images/Character/cardSd_b.png
  src/assets/images/Character/cardSd_c.png
  src/assets/images/Character/cardSd_d.png
  src/assets/images/Character/cardSd_e.png
  src/assets/images/Character/characterPage.png
  src/assets/images/Duck.png
  src/assets/images/DuckBubble.png
  src/assets/images/scrollbar_thumb.png
  src/assets/images/scrollbar_track.png
  src/assets/images/startIcon.png
  src/index.css
  src/main.tsx
  src/pages/CaseSelectPage.tsx
  src/pages/LoginPage.tsx
  src/pages/MainPage.tsx
  src/pages/RegisterPage.tsx
  src/pages/StartPage.tsx
Labels: 🎨Design

#22 design: 기존 페이지 코드 수정
  src/App.tsx
  src/assets/images/others/bubble_s.png
  src/pages/ALoadingPage.tsx
  src/pages/CaseSelectPage.tsx
  src/pages/DLoadingPage.tsx
  src/pages/LLoadingPage.tsx
  src/pages/LoginPage.tsx
  src/pages/MainPage.tsx
  src/pages/RegisterPage.tsx
  src/pages/StartPage.tsx
Labels: 🎨Design

#25 Design/#21 결과페이지 퍼블리싱
  package.json
  src/.DS_Store
  src/App.tsx
  src/assets/images/Duck/Duck.png
  src/assets/images/Duck/DuckBubble.png
  src/assets/images/background/myPage.png
  src/assets/images/background/resultPage.png
  src/assets/images/icon/homeIcon.png
  src/assets/images/icon/saveIcon.png
  src/assets/images/icon/shareIcon.png
  src/assets/images/icon/startIcon.png
  src/components/PieChart.tsx
  src/pages/MainPage.tsx
  src/pages/MyPage.tsx
  src/pages/ResultPage.tsx
  yarn.lock
Labels: 🎨Design

#27 design: 대화페이지 퍼블리싱
  src/App.tsx
  src/assets/images/icon/nextIcon.png
  src/assets/images/others/talkImg.png
  src/pages/MainPage.tsx
  src/pages/SelectPage.tsx
  src/pages/TalkPage.tsx
Labels: 🎨Design

#30 [design/#29] 카드 애니메이션 추가
  src/assets/images/Character/cardBack_1.png
  src/assets/images/Character/cardBack_3.png
  src/assets/images/Character/cardBack_4.png
  src/assets/images/Character/cardBack_5.png
  src/assets/images/Character/cardBack_6.png
  src/assets/images/Character/cardBack_7.png
  src/assets/images/Character/cardBack_8.png
  src/assets/images/Character/cardBack_9.png
  src/assets/images/Character/cardSd_1.png
  src/assets/images/Character/cardSd_2.png
  src/assets/images/Character/cardSd_3.png
  src/assets/images/Character/cardSd_4.png
  src/assets/images/Character/cardSd_5.png
  src/assets/images/Character/cardSd_6.png
  src/assets/images/Character/cardSd_7.png
  src/assets/images/Character/cardSd_8.png
  src/assets/images/Character/cardSd_9.png
  src/assets/images/Character/cardSd_a.png
  src/assets/images/Character/cardSd_b.png
  src/assets/images/Character/cardSd_c.png
  src/assets/images/Character/cardSd_d.png
  src/assets/images/Character/cardSd_e.png
  src/index.css
  src/pages/MainPage.tsx
  src/pages/MyPage.tsx
Labels: 🎨Design

#36 [design/#35] 아침 대화 페이지 구현
  src/App.tsx
  src/assets/images/others/input_ui.png
  src/assets/images/others/script_ui.png
  src/assets/images/others/sendbutton_ui.png
  src/assets/images/others/sendbutton_ui_a.png
  src/components/CharacterModal.tsx
  src/index.css
  src/pages/CharacterPage.tsx
  src/pages/MorningPage.tsx
Labels: 🎨Design

#44 [design/#43] 디자인 수정 및 코드 수정
  src/assets/images/standing/cha.png
  src/components/CharacterModal.tsx
  src/components/ELoadingModal.tsx
  src/components/LLoadingModal.tsx
  src/index.css
  src/pages/MorningPage.tsx
  src/pages/ResultPage.tsx
Labels: 🎨Design

#46 [design/#40] 마이페이지 카드 애니메이션 추가
  src/App.tsx
  src/assets/images/Character/card_1.png
  src/assets/images/Character/card_3.png
  src/assets/images/Character/card_4.png
  src/assets/images/Character/card_5.png
  src/assets/images/Character/card_6.png
  src/assets/images/Character/card_7.png
  src/assets/images/Character/card_8.png
  src/assets/images/Character/card_9.png
  src/assets/images/background/myPage.png
  src/assets/images/background/myPageImg.png
  src/assets/images/background/resultPage.png
  src/assets/images/others/memberCard.png
  src/assets/images/others/userPhoto.png
  src/components/PieChart.tsx
  src/pages/MainPage.tsx
  src/pages/MyPage.tsx
Labels: 🎨Design

#54 [design/#53] 페이지 라우팅 적용
  src/components/FeedBackLuModal.tsx
  src/components/FeedBackMoModal.tsx
  src/pages/LoginPage.tsx
  src/pages/LunchTalkPage.tsx
  src/pages/MainPage.tsx
  src/pages/MorningPage.tsx
  src/pages/RegisterPage.tsx
  src/pages/StartPage.tsx
Labels: 🎨Design

#55 [design/#52] 결과 페이지 수정 및 기타 코드 수정
  src/assets/images/background/minipage_r.png
  src/assets/images/others/memberCard_r.png
  src/assets/images/others/memberCard_strap.png
  src/assets/images/others/sharebutton_ui.png
  src/assets/images/others/sharebutton_ui_p.png
  src/assets/images/others/strap.png
  src/components/FeedBackEvModal.tsx
  src/components/FeedBackLuModal.tsx
  src/components/FeedBackMoModal.tsx
  src/components/ResultLoadingModal.tsx
  src/index.css
  src/pages/EveningPage.tsx
  src/pages/LunchTalkPage.tsx
  src/pages/ResultPage.tsx
  src/pages/StartPage.tsx
Labels: 🎨Design

#58 [design/#57]: 디자인 수정 및 코드 수정
  src/components/FeedBackMoModal.tsx
  src/components/ResultLoadingModal.tsx
  src/index.css
  src/pages/LoginPage.tsx
  src/pages/RegisterPage.tsx
  src/pages/ResultPage.tsx
Labels: 🎨Design

#61 [feat/#59] 로그인 api 연동
  package-lock.json
  src/pages/LoginPage.tsx
Labels: ✨Feat

#63 [design/#62] 로그인, 회원가입 및 디자인 수정
  src/components/CharacterModal.tsx
  src/index.css
  src/pages/LoginPage.tsx
  src/pages/RegisterPage.tsx
  src/pages/ResultPage.tsx
  src/pages/StartPage.tsx
Labels: 🎨Design

#67 [feat/#] 대화 시작 api 연동
  src/components/CharacterModal.tsx
  src/pages/MainPage.tsx
  src/pages/MorningPage.tsx
Labels: ✨Feat

#68 [feat/#66] 아이디 중복확인 api 연동
  src/pages/RegisterPage.tsx
Labels: ✨Feat

#71 [design/#69] 구현한 기능
  src/assets/images/standing/om.png
  src/assets/images/standing/ow.png
  src/components/CharacterModal.tsx
  src/pages/MorningPage.tsx
Labels: 🎨Design

#73 [design/#72] StartPage 디자인 수정
  src/assets/images/others/logo.png
  src/assets/images/others/logo_i.png
  src/pages/StartPage.tsx
Labels: 🎨Design

#75 [design/#74] 카메라 모달 페이지 구현
  package-lock.json
  package.json
  src/assets/images/others/memberCard_strap_s.png
  src/components/CameraModal.tsx
  src/pages/EveningPage.tsx
  src/pages/LoginPage.tsx
  src/pages/LunchTalkPage.tsx
  src/pages/MainPage.tsx
  src/pages/RegisterPage.tsx
  yarn.lock
Labels: 🎨Design

#77 [feat/#76] 다음 상황 api 연동
  src/components/CharacterModal.tsx
  src/components/FeedBackEvModal.tsx
  src/components/FeedBackLuModal.tsx
  src/components/FeedBackMoModal.tsx
  src/pages/EveningPage.tsx
  src/pages/LunchTalkPage.tsx
  src/pages/MainPage.tsx
  src/pages/MorningPage.tsx
  src/pages/RegisterPage.tsx
Labels: ✨Feat

#79 [feat/#78] 사원증 사진 등록 api 연동
  src/components/CameraModal.tsx
  src/pages/MorningPage.tsx
Labels: ✨Feat

#83 [feat/#70] 웹소켓 연결
  src/components/CameraModal.tsx
  src/components/FeedBackEvModal.tsx
  src/pages/EveningPage.tsx
  src/pages/LunchTalkPage.tsx
  src/pages/MainPage.tsx
  src/pages/MorningPage.tsx
  yarn.lock
Labels: ✨Feat

#86 [feat/#84] 점심 대화페이지 웹소켓 연결 & 다음 상황 api 연동
  src/components/FeedBackMoModal.tsx
  src/pages/LunchTalkPage.tsx
  src/pages/MainPage.tsx
  src/pages/MorningPage.tsx
Labels: ✨Feat

#90 [feat/#89] 저녁페이지 다음 상황 api 연동
  src/pages/EveningPage.tsx
Labels: ✨Feat

#91 [feat/#89] 저녁페이지 코드 수정
  src/pages/EveningPage.tsx
Labels: ✨Feat

#93 [feat/#85] 결과지 생성 api 연동
  package.json
  src/components/CameraModal.tsx
  src/components/ResultLoadingModal.tsx
  src/hooks/axiosInstance.ts
  src/pages/EveningPage.tsx
  src/pages/MorningPage.tsx
  src/pages/ResultPage.tsx
  yarn.lock
Labels: ✨Feat

#95 [feat/#94] jwt 토큰 일괄 적용
  src/pages/EveningPage.tsx
  src/pages/LunchPage.tsx
  src/pages/RegisterPage.tsx
  src/pages/ResultPage.tsx
Labels: ✨Feat

#97 [feat/#96] 카카오 공유하기 구현
  .gitignore
  index.d.ts
  index.html
  src/pages/EveningPage.tsx
  src/pages/RegisterPage.tsx
  src/pages/ResultPage.tsx
  tsconfig.json
Labels: ✨Feat

#101 [feat/#98] 결과 조회 api 연동
  src/App.tsx
  src/pages/MyPage.tsx
  src/pages/UserResultPage.tsx
Labels: ✨Feat

#103 [feat/#100] 캐릭터 대사 음성 적용
  src/pages/EveningPage.tsx
  src/pages/LunchPage.tsx
  src/pages/MorningPage.tsx
Labels: ✨Feat

#104 [feat/#102] 시뮬레이션 결과 카카오톡 공유 구현
  src/App.tsx
  src/assets/images/others/simulbutton_ui.png
  src/assets/images/others/simulbutton_ui_p.png
  src/pages/ResultPage.tsx
  src/pages/SharedResultPage.tsx
  src/utils/shareKakao.ts
Labels: ✨Feat

#107 [design/#105] 로그아웃 버튼 추가
  src/pages/MainPage.tsx
  src/pages/MyPage.tsx
Labels: 🎨Design

#109 [feat/#107] 로그아웃 api 연동
  index.html
  src/pages/MainPage.tsx
  src/pages/MyPage.tsx
Labels: ✨Feat

#111 [fix/#110] 시뮬레이션 중 사용자 입력 문제해결
  src/pages/EveningPage.tsx
  src/pages/LunchPage.tsx
  src/pages/MorningPage.tsx
Labels: ✨Feat

#112 [fix/#106] 피드백 버튼 잠금 설정
  src/pages/EveningPage.tsx
  src/pages/LunchPage.tsx
  src/pages/MorningPage.tsx
Labels: ❤️‍🔥Fix

#115 [fix/#113] 로그인 에러 메세지 수정
  src/pages/LoginPage.tsx
Labels: ❤️‍🔥Fix

#117 [design/#116] 촬영 모달 버튼 위치 수정
  src/assets/images/others/memberCard_s.png
  src/assets/images/others/strap_s.png
  src/components/CameraModal.tsx
  src/pages/MainPage.tsx
Labels: 🎨Design

#119 [design/#114]
  src/App.tsx
  src/assets/images/others/coffee.png
  src/components/CustomCursor.tsx
  src/index.css
  src/main.tsx
  src/pages/StartPage.tsx
Labels: 🎨Design

#121 [design/#120] 버튼 효과음 적용
  src/App.tsx
  src/pages/EveningPage.tsx
  src/pages/LunchPage.tsx
  src/pages/MorningPage.tsx
  src/pages/MyPage.tsx
Labels: 🎨Design

#127 [refactor/#126]: api 호출 변경
  src/components/CameraModal.tsx
  src/hooks/axiosInstance.ts
  src/pages/EveningPage.tsx
  src/pages/LoginPage.tsx
  src/pages/LunchPage.tsx
  src/pages/MainPage.tsx
  src/pages/MorningPage.tsx
  src/pages/MyPage.tsx
  src/pages/RegisterPage.tsx
  src/pages/ResultPage.tsx
  src/pages/SharedResultPage.tsx
Labels: 🔨Refactor

#131 [fix/#130] asset적용 import로 변경
  src/components/CameraModal.tsx
  src/components/CharacterModal.tsx
  src/components/ResultLoadingModal.tsx
  src/pages/EveningPage.tsx
  src/pages/LoginPage.tsx
  src/pages/LunchPage.tsx
  src/pages/MorningPage.tsx
  src/pages/MyPage.tsx
  src/pages/RegisterPage.tsx
  src/pages/ResultPage.tsx
  src/pages/SharedResultPage.tsx
  src/pages/StartPage.tsx
  src/pages/UserResultPage.tsx
Labels: ❤️‍🔥Fix

#139 [fix/#138] 비밀번호 valid 처리
  dist/assets/index-C9hoGwW6.js
  dist/index.html
  src/pages/RegisterPage.tsx
Labels: ❤️‍🔥Fix

#141 [fix/#140] UserResultPage 버튼 오류 수정
  src/pages/UserResultPage.tsx
  src/utils/shareKakao.ts
Labels: ❤️‍🔥Fix

#145 [design/#144] 시작페이지 반응형 레이아웃 구현
  src/assets/images/background/bg_stand1.png
  src/assets/images/background/bg_stand2.png
  src/assets/images/background/bg_stand3.png
  src/assets/images/background/bg_stand4.png
  src/index.css
  src/pages/StartPage.tsx
  tailwind.config.js
Labels: 🎨Design

#154 [design/#147] 메인페이지 반응형 적용
  src/index.css
  src/pages/MainPage.tsx
  tailwind.config.js
Labels: 🎨Design

#155 [design/#153] 저녁 페이지 반응형 레이아웃 적용
  dist/assets/Chatbar-CvypGhZp.png
  dist/assets/index-BlzKclrx.css
  dist/assets/index-DzMY6Jrg.js
  dist/assets/index-S38Zmj95.css
  dist/assets/index-U3wS79tW.js
  dist/index.html
  src/assets/images/others/Chatbar.png
  src/assets/images/others/memberCard_strap.png
  src/assets/images/others/memberCard_strap_s.png
  src/assets/images/others/script_ui.png
  src/assets/images/others/userPhoto.png
  src/assets/images/standing/cha.png
  src/assets/images/standing/duck_s.png
  src/components/CameraModal.tsx
  src/components/ELoadingModal.tsx
  src/components/FeedBackEvModal.tsx
  src/components/LLoadingModal.tsx
  src/pages/EveningPage.tsx
  src/pages/LunchPage.tsx
Labels: 🎨Design

#163 [design/#156] 결과페이지 반응형 적용
  src/pages/ResultPage.tsx
Labels: 🎨Design

#165 [design/#164]: 마이페이지 반응형 적용
  src/pages/MyPage.tsx
Labels: 🎨Design
