Repository 2024-Summer-Bootcamp-Team-O/Frontend, pull requests merged in 2024-08, with the labels that each got.

#169 [design/#168] ResultLoading 반응형 대응
  dist/assets/index-BqCU1Cng.css
  dist/assets/index-DM2Bjx6o.css
  dist/assets/index-DZPKYdS1.js
  dist/index.html
  src/assets/images/subway.png
  src/components/ResultLoadingModal.tsx
  src/index.css
Labels: 🎨Design

#171 [design/#170] ResultLoading 이미지 import
  dist/assets/index-C0Di36mC.js
  dist/assets/subway-6lZtbFbE.png
  dist/index.html
  src/components/ResultLoadingModal.tsx
Labels: 🎨Design

#175 [feat#174] 이미지 드래그 시 잔상 방지
  dist/assets/index-9WLnTLIg.js
  dist/assets/index-BkM-a_Mp.css
  dist/assets/index-Cs-6jRRZ.css
  dist/index.html
  src/index.css
Labels: ✨Feat

#178 [refactor/#176] 버튼 수정
  src/pages/MyPage.tsx
  src/pages/ResultPage.tsx
Labels: 🔨Refactor

#182 [design/#181]:반응형 수정
  src/pages/MainPage.tsx
  src/pages/MyPage.tsx
Labels: 🎨Design

#184 [design/#183] 공유결과페이지 반응형 적용
  src/pages/SharedResultPage.tsx
Labels: 🎨Design
